### ISSUE TITLE
Template colors?

### ISSUE THREAD

**Issue by noizo** [Sordie/AWSume#1]
Hi, glad i'm the first one 🥇 
I was thinking about coloring output.
Any way to make it a bit less aggressive?

![Screenshot from 2022-08-29 14-48-28](https://user-images.githubusercontent.com/1682474/187205046-5d998bb0-c8ef-4b48-b19b-852de4af3671.png)

I'm using powerlevel10k template.

I found out that it's possible to show it only when i use command, which is fine for me:
```
POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform|as|awsume'
```
However templating would be nice anyway :)

Figured out how to template it from theme settings.
Can close now :)

**Comment by Sordie** [comment]
Alright, great that could already solve it :)
