### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by DJKaswa** [Sordie/AWSume#2]
1. Should just the function in brackets be added or the if/else statement at the bottom added too?
2. Where should the function be added while in the chosen theme's code, bottom of the code?

**Comment by Sordie** [comment]
Sorry for the late reply, I have added a usage example to the README.
1.	You should place the `awsume.plugin.zsh` file in your custom plugins folder.
2.	You can then use the function in your themes prompt.

If you don’t care much about the customizability, I would recommend you checkout the [powerlevel10k](https://github.com/romkatv/powerlevel10k) as well. The powerlevel10k theme has a build in option to display the `AWSUME_PROFILE` and should be easier to setup.
